### ISSUE TITLE
Openapi (swagger) documentation does not include server urls

### ISSUE THREAD

**Issue by andre-stefanov** [NearBuyVsVirus/nearbuy-backend#31]
Without a baseUrl the generated client code has to be modified otherwise "localhost" will be used.

Documentation for desired properties can be found [here](https://swagger.io/docs/specification/api-host-and-base-path/).

**Comment by fanick-ber** [comment]
improved to env variable in https://github.com/NearBuyVsVirus/nexd-backend/pull/44
